variables:
  image_size: &image_size 64
  n_class: &n_class 2

model:
  name: CBIS_CSNN
  module_name: src.models.csnn
  parameters: 
    input_shape: !!python/tuple [1, *image_size, *image_size]
    n_hidden: 16
    n_output: *n_class
    beta: 0.8
    timesteps: 50
    encoding_type: 

dataset:
  name: ImageFolder
  module_name: torchvision.datasets
  parameters:
    data_dir: /home/nvidia/projects/Research/AROB-CBIS-DDSM-Preparation/data/roi-mass-severity
    image_size: *image_size
    batch_size: 64
    mean: 0.1307
    std: 0.3081

experiment:
  name: BinaryClassificationExperiment
  module_name: src.experiment.base
  parameters:
    num_epochs: 1
    lr: .001
    seed: 1234
    log_dir: ./logs