variables:
  image_size: &image_size 128
  n_class: &n_class 4
  
model:
  name: CSNN_3C
  parameters: 
    in_shape: !!python/tuple [1, *image_size, *image_size]
    n_class: *n_class
    start_features: 16
    beta: 0.5
    k_size: 3

dataset:
  name: CBIS
  parameters:
    data_dir: /home/nvidia/projects/Research/AROB-CBIS-DDSM-Preparation/data/roi-severity/
    image_size: *image_size
    batch_size: 16
    mean: 0.5451
    std: 0.1577

experiment:
  name: CBIS
  parameters:
    log_dir: ./logs
    seed: 1234
    epochs: 10
    lr: .001
    num_steps: 50
    encoding: rate