variables:
  image_size: &image_size 128
  n_class: &n_class 2

model:
  name: ShallowCNN
  module_name: src.models.cnn
  parameters: 
    num_classes: *n_class

dataset:
  name: ImageFolder
  module_name: torchvision.datasets
  parameters:
    data_dir: /home/nvidia/projects/Research/AROB-CBIS-DDSM-Preparation/data/roi-calc-severity
    image_size: *image_size
    batch_size: 64
    mean: 0.5
    std: 0.5

experiment:
  name: CNNExperiment
  module_name: src.experiment.cnn
  parameters:
    num_epochs: 5
    lr: .001
    seed: 1234
    log_dir: ./logs