variables:
  image_size: &image_size 32
  n_class: &n_class 10
  
model:
  name: CSNN_2C
  parameters: 
    in_shape: !!python/tuple [1, *image_size, *image_size]
    n_class: *n_class
    start_features: 16
    beta: 0.5
    k_size: 5

dataset:
  name: CIFAR10
  parameters:
    data_dir: ./data
    image_size: *image_size
    batch_size: 128
    mean: 0.1307
    std: 0.3081

experiment:
  name: CIFAR10
  parameters:
    log_dir: ./logs
    seed: 1234
    epochs: 1
    lr: .001
    num_steps: 50
    encoding: rate