variables:
  image_size: &image_size 28
  n_class: &n_class 10

model:
  name: FMNIST_CNN
  module_name: src.models.cnn
  parameters:
    n_input: 1
    n_output: *n_class

dataset:
  name: FashionMNIST
  module_name: torchvision.datasets
  parameters:
    data_dir: ./data
    image_size: *image_size
    batch_size: 128
    mean: 0.5
    std: 0.5

experiment:
  name: CNNExperiment
  module_name: src.experiment.cnn
  parameters:
    num_epochs: 5
    lr: 0.001
    seed: 1234
    log_dir: ./logs