variables:
  image_size: &image_size 224
  n_class: &n_class 4
  n_input: &n_input 1

model:
  name: CNN_F
  module_name: src.models.torch
  parameters:
    n_input: *n_input
    n_output: *n_class
    in_size: *image_size

dataset:
  name: CustomImageFolder
  module_name: src.datasets.custom
  parameters:
    root: ../AROB-CBIS-DDSM-Preparation/data/scan-severity
    image_size: *image_size
    augment_type: all

dataloader:
  parameters:
    batch_size: 32

experiment:
  name: CNNExperiment
  module_name: src.experiment.torch
  parameters:
    num_epochs: 80
    lr: .0001
    weight_decay: 0
    seed: 1234
    log_dir: ./logs
    k_fold: 0
    early_stopping_patience: 20