variables:
  image_size: &image_size 256
  n_class: &n_class 3
  n_input: &n_input 1

model:
  name: MNET10
  module_name: src.models.torch
  parameters:
    n_input: *n_input
    n_output: *n_class
    in_size: *image_size

dataset:
  name: VindrDicomDataset
  module_name: src.datasets.custom
  parameters:
    data_dir: /mnt/d/datasets/vindr-mammo/data
    image_size: *image_size
    class_list: ['no_finding', 'suspicious_calcification', 'mass']
dataloader:
  parameters:
    batch_size: 8

experiment:
  name: CNNExperiment
  module_name: src.experiment.torch
  parameters:
    num_epochs: 100
    lr: .0005
    weight_decay: .0001
    seed: 1234
    log_dir: ./logs
    suffix: