variables:
  image_size: &image_size 224
  n_class: &n_class 4
  n_input: &n_input 3

model:
  name: MNET10_3Conv
  module_name: src.models.cnn
  parameters:
    n_input: *n_input
    n_output: *n_class
    in_size: *image_size

dataset:
  name: ImageFolder
  module_name: torchvision.datasets
  parameters:
    data_dir: /home/nvidia/projects/Research/AROB-CBIS-DDSM-Preparation/data/scan-severity_synthetized
    image_size: *image_size
    batch_size: 32
    channels: *n_input
    mean: 0.5457
    std: 0.1635
    use_augmentations: true

experiment:
  name: CNNExperiment
  module_name: src.experiment.cnn
  parameters:
    num_epochs: 100
    lr: .0001
    seed: 1234
    log_dir: ./logs
    suffix: scan_synthetized_aug