variables:
  image_size: &image_size 224
  n_class: &n_class 4
  n_input: &n_input 1

model:
  name: MNET10
  module_name: src.models.torch
  parameters:
    n_input: *n_input
    n_output: *n_class
    in_size: *image_size

dataset:
  name: ImageFolder
  module_name: torchvision.datasets
  parameters:
    data_dir: /home/nvidia/Projects/expe_Brad/AROB-CBIS-DDSM-Preparation/data/scan-severity
    image_size: *image_size
    batch_size: 64
    channels: *n_input

experiment:
  name: CNNExperiment
  module_name: src.experiment.torch
  parameters:
    num_epochs: 100
    lr: .0005
    weight_decay: .0001
    seed: 1234
    log_dir: ./logs
    suffix: scan_raw