variables:
  image_size: &image_size 224
  n_class: &n_class 3
  n_input: &n_input 1

model:
  name: VGG16
  module_name: src.models.torch
  parameters:
    n_input: *n_input
    n_output: *n_class
    in_size: *image_size

dataset:
  name: CustomImageFolder
  module_name: src.datasets.custom
  parameters:
    root: /mnt/d/datasets/vindr-mammo/data/prepared
    image_size: *image_size

dataloader:
  parameters:
    batch_size: 32

experiment:
  name: CNNExperiment
  module_name: src.experiment.torch
  parameters:
    num_epochs: 100
    lr: .0001
    weight_decay: .0001
    seed: 1234
    log_dir: ./logs
    suffix: 