variables:
  image_size: &image_size 28
  n_class: &n_class 10

model:
  name: FCSNN
  module_name: src.models.fsnn
  parameters: 
    n_input: *image_size
    n_hidden: 1000
    n_output: *n_class
    beta: 0.8
    timesteps: 50
    encoding_type: rate

dataset:
  name: MNIST
  module_name: torchvision.datasets
  parameters:
    data_dir: ./data
    image_size: *image_size
    batch_size: 128
    mean: 0.1307
    std: 0.3081

experiment:
  name: SNNExperiment
  module_name: src.experiment.base
  parameters:
    num_epochs: 1
    lr: .001
    seed: 1234
    log_dir: ./logs