variables:
  image_size: &image_size 64
  n_class: &n_class 10
  n_input: &n_input 1

model:
  name: S_MNET10
  module_name: src.models.snnTorch
  parameters:
    input_shape: !!python/tuple [*n_input, *image_size, *image_size]
    n_output: *n_class
    n_steps: 5
    beta: 0.5
    encoding_type:

dataset:
  name: CIFAR10
  module_name: torchvision.datasets
  parameters:
    data_dir: ./data
    image_size: *image_size
    batch_size: 8
    channels: *n_input
    mean: 0.5
    std: 0.5
    use_augmentations: false

experiment:
  name: SNNExperiment
  module_name: src.experiment.snnTorch
  parameters:
    num_epochs: 100
    lr: .0005
    weight_decay: .0001
    seed: 1234
    log_dir: ./logs
    suffix: scan_raw