variables:
  image_size: &image_size 224
  n_class: &n_class 3
  n_input: &n_input 1

model:
  name: SimpleSpikingMNET
  module_name: src.models.jelly
  parameters:
    input_shape: !!python/tuple [*n_input, *image_size, *image_size]
    n_output: *n_class
    n_steps: 5
    encoding_method: latency
dataset:
  name: CustomImageFolder
  module_name: src.datasets.custom
  parameters:
    root: '/mnt/d/datasets/Vindr/prepared/vindr/lesions/'
    image_size: *image_size
    augment_type: all

dataloader:
  parameters:
    batch_size: 16

experiment:
  name: SJellyExperiment
  module_name: src.experiment.jelly
  parameters:
    num_epochs: 37
    lr: .0001
    weight_decay: 0
    seed: 1234
    log_dir: ./logs
    early_stopping_patience: 20