variables:
  image_size: &image_size 224
  n_class: &n_class 4
  n_input: &n_input 1

model:
  name: SimpleSpikingMNET
  module_name: src.models.jelly
  parameters:
    input_shape: !!python/tuple [*n_input, *image_size, *image_size]
    n_output: *n_class
    n_steps: 10
    encoding_method: 'poisson'

dataset:
  name: CustomImageFolder
  module_name: src.datasets.custom
  parameters:
    root: ../AROB-Breast-Datasets/data/cbis/lesions-severity
    image_size: *image_size
    augment_type: 

dataloader:
  parameters:
    batch_size: 32

experiment:
  name: SJellyExperiment
  module_name: src.experiment.jelly
  parameters:
    num_epochs: 80
    lr: .0001
    weight_decay: 0
    seed: 1234
    log_dir: ./logs
    k_fold: 0
    early_stopping_patience: 20