variables:
  image_size: &image_size 224
  n_class: &n_class 4
  n_input: &n_input 3

model:
  name: SJellyCSNN
  module_name: src.models.jelly
  parameters:
    input_shape: !!python/tuple [*n_input, *image_size, *image_size]
    n_output: *n_class
    n_steps: 5

dataset:
  name: ImageFolder
  module_name: torchvision.datasets
  parameters:
    data_dir: /home/nvidia/Projects/expe_Brad/AROB-CBIS-DDSM-Preparation/data/roi-severity_synthetized
    image_size: *image_size
    batch_size: 32
    channels: *n_input

experiment:
  name: SJellyExperiment
  module_name: src.experiment.jelly
  parameters:
    num_epochs: 50
    lr: .0001
    weight_decay: 0.0001
    seed: 1234
    log_dir: ./logs
    suffix: scan_raw